name: Build Docker image.

on:
  workflow_call:
    inputs:
      DOCKERFILE:
        required: true
        type: string
      IMAGE_NAME:
        required: true
        type: string
      PROJECT_NAME:
        required: true
        type: string

env:
  CONTAINER_REGISTRY: "registry.digitalocean.com/tmsolution-cr"

jobs:
  compute_tag:
    name: Compute tag.
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' }}
    # Map a step output to a job output
    outputs:
      TAG: ${{ steps.build-tag.outputs.tag-output }}      
    steps:
      - id: build-tag
        run: echo "tag-output=$(echo $GITHUB_SHA | head -c7)" >> $GITHUB_OUTPUT
        
  docker-build:
    name: Build docker image.
    runs-on: ubuntu-latest
    needs: compute_tag
    steps:      
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Download app artifacts
        uses: actions/download-artifact@v3
        with:
          name: app-artifacts
          path: ${{inputs.PROJECT_NAME}}/bin/Release/net6.0/publish/    
      - name: Test
        run: echo ${{inputs.PROJECT_NAME}}/bin/Release/net6.0/publish/
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and release docker image
        uses: docker/build-push-action@v3
        with:
          file: ${{ inputs.DOCKERFILE }}
          context: .
          tags: ${{env.CONTAINER_REGISTRY}}/${{inputs.IMAGE_NAME}}:${{needs.compute_tag.outputs.TAG}}
          outputs: type=docker,dest=/tmp/${{ inputs.IMAGE_NAME }}.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.IMAGE_NAME }}
          path: /tmp/${{ inputs.IMAGE_NAME }}.tar
