name: Build gradle application

on:
  workflow_call:
    inputs:
      JAVA_VERSION:
        type: string
        default: '17'
      GRADLE_TASK:
        type: string
        default: 'build'
    secrets:
      USERNAME:
        required: false
      PASSWORD:
        required: false

jobs:
  gradle-build:
    name: Building gradle application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.JAVA_VERSION }}
          distribution: 'temurin'
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        with:
          arguments: ${{ inputs.GRADLE_TASK }} --no-daemon --parallel
          
