name: Build gradle application

on:
  workflow_call:
    inputs:
      JAVA_VERSION:
        type: string
        default: '17'
      GRADLE_TASK:
        type: string
        default: 'build'

jobs:
  gradle-build:
    name: Building gradle application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.JAVA_VERSION }}
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ${{ inputs.GRADLE_TASK }} --no-daemon --parallel
          
  publish:
    if: ${{ always() }}
    needs: gradle-build
    name: Publish test results
    runs-on: ubuntu-latest
    steps:
      - uses: actions/upload-artifact@v1
        with:
          name: Unit test report
          path: build/reports/tests/test/index.html
